[package]
name = "test_asset"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_asset_loader = { version = "0.20", features = ["2d"] }

[dependencies.bevy]
version = "0.13"
default-features = false
features = [
    "bevy_asset",
    "bevy_winit",
    "png",
#    "multi-threaded",
]
