[package]
name = "test_asset"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.13"
default-features = false
features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_render",
    "bevy_sprite",
    "png",
    "x11",
#    "multi-threaded",
]
